package funcs

import "strings"

func init() {
	register("stringsCompare", strings.Compare)
	register("stringsContains", strings.Contains)
	register("stringsContainsAny", strings.ContainsAny)
	register("stringsContainsRune", strings.ContainsRune)
	register("stringsCount", strings.Count)
	register("stringsEqualFold", strings.EqualFold)
	register("stringsFields", strings.Fields)
	register("stringsHasPrefix", strings.HasPrefix)
	register("stringsHasSuffix", strings.HasSuffix)
	register("stringsIndex", strings.Index)
	register("stringsIndexAny", strings.IndexAny)
	register("stringsIndexByte", strings.IndexByte)
	register("stringsIndexRune", strings.IndexRune)
	register("stringsJoin", strings.Join)
	register("stringsLastIndex", strings.LastIndex)
	register("stringsLastIndexAny", strings.LastIndexAny)
	register("stringsLastIndexByte", strings.LastIndexByte)
	register("stringsMap", strings.Map)
	register("stringsRepeat", strings.Repeat)
	register("stringsReplace", strings.Replace)
	register("stringsSplit", strings.Split)
	register("stringsSplitAfter", strings.SplitAfter)
	register("stringsSplitAfterN", strings.SplitAfterN)
	register("stringsSplitN", strings.SplitN)
	register("stringsTitle", strings.Title)
	register("stringsToLower", strings.ToLower)
	register("stringsToLowerSpecial", strings.ToLowerSpecial)
	register("stringsToTitle", strings.ToTitle)
	register("stringsToTitleSpecial", strings.ToTitleSpecial)
	register("stringsToUpper", strings.ToUpper)
	register("stringsToUpperSpecial", strings.ToUpperSpecial)
	register("stringsTrim", strings.Trim)
	register("stringsTrimLeft", strings.TrimLeft)
	register("stringsTrimPrefix", strings.TrimPrefix)
	register("stringsTrimRight", strings.TrimRight)
	register("stringsTrimSpace", strings.TrimSpace)
	register("stringsTrimSuffix", strings.TrimSuffix)
}
